version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: DefrostedApp
    restart: always
    environment:
      - POSTGRES_DB=defrosted
      - POSTGRES_USER=defrosted
      - POSTGRES_PASSWORD=defrosted
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
